export const GetRandomComment = () => {
  var quotes = [
    "Hey everyone, how's it going?",
    "Shoutout from [Your City]!",
    "The quality of this stream is 🔥",
    "Can you play [song/game] next?",
    "Is anyone else having buffering issues?",
    "This is so funny 😂",
    "Love your content! Keep it up!",
    "What's your favorite [movie/game/book]?",
    "Mods, where are you? We need help!",
    "First time catching you live! So excited!",
    "Please notice me!",
    "Can you give me a shoutout?",
    "This chat is going crazy!",
    "Who's here from [another channel/social media]?",
    "How can I donate?",
    "This music is awesome!",
    "I love the community here!",
    "Anyone else watching while working?",
    "The stream is lagging for me.",
    "Thanks for the stream, you're amazing!",
    "Adarsh mehnat kiya hai 🔥",
    "Who's ready for the next part?",
    "Can you do a Q&A session?",
    "This chat is moving so fast!",
    "I just subscribed! 🔔",
    "When's your next stream?",
    "What time zone are you in?",
    "I can't believe this is happening live!",
    "What setup are you using?",
    "Anyone else here from [another country]?",
    "I missed the beginning, what happened?",
    "Can you turn up the volume a bit?",
    "This is my favorite part!",
    "How long will the stream be?",
    "Let's get this stream to 1,000 likes!",
    "Can you react to [a video]?",
    "You should collaborate with [another creator].",
    "I've been watching since the beginning!",
    "The chat is lit tonight!",
    "What's your next big project?",
    "Thank you for the stream, it made my day!",
  ];

  var num = Math.floor(Math.random() * 40);
  return quotes[num];
};

export function GenerateRandomName() {
  var nameList = [
    "Time",
    "Past",
    "Future",
    "Dev",
    "Fly",
    "Flying",
    "Soar",
    "Soaring",
    "Power",
    "Falling",
    "Fall",
    "Jump",
    "Cliff",
    "Mountain",
    "Rend",
    "Red",
    "Blue",
    "Green",
    "Yellow",
    "Gold",
    "Demon",
    "Demonic",
    "Panda",
    "Cat",
    "Kitty",
    "Kitten",
    "Zero",
    "Memory",
    "Trooper",
    "XX",
    "Bandit",
    "Fear",
    "Light",
    "Glow",
    "Tread",
    "Deep",
    "Deeper",
    "Deepest",
    "Mine",
    "Your",
    "Worst",
    "Enemy",
    "Hostile",
    "Force",
    "Video",
    "Game",
    "Donkey",
    "Mule",
    "Colt",
    "Cult",
    "Cultist",
    "Magnum",
    "Gun",
    "Assault",
    "Recon",
    "Trap",
    "Trapper",
    "Redeem",
    "Code",
    "Script",
    "Writer",
    "Near",
    "Close",
    "Open",
    "Cube",
    "Circle",
    "Geo",
    "Genome",
    "Germ",
    "Spaz",
    "Shot",
    "Echo",
    "Beta",
    "Alpha",
    "Gamma",
    "Omega",
    "Seal",
    "Squid",
    "Money",
    "Cash",
    "Lord",
    "King",
    "Duke",
    "Rest",
    "Fire",
    "Flame",
    "Morrow",
    "Break",
    "Breaker",
    "Numb",
    "Ice",
    "Cold",
    "Rotten",
    "Sick",
    "Sickly",
    "Janitor",
    "Camel",
    "Rooster",
    "Sand",
    "Desert",
    "Dessert",
    "Hurdle",
    "Racer",
    "Eraser",
    "Erase",
    "Big",
    "Small",
    "Short",
    "Tall",
    "Sith",
    "Bounty",
    "Hunter",
    "Cracked",
    "Broken",
    "Sad",
    "Happy",
    "Joy",
    "Joyful",
    "Crimson",
    "Destiny",
    "Deceit",
    "Lies",
    "Lie",
    "Honest",
    "Destined",
    "Bloxxer",
    "Hawk",
    "Eagle",
    "Hawker",
    "Walker",
    "Zombie",
    "Sarge",
    "Capt",
    "Captain",
    "Punch",
    "One",
    "Two",
    "Uno",
    "Slice",
    "Slash",
    "Melt",
    "Melted",
    "Melting",
    "Fell",
    "Wolf",
    "Hound",
    "Legacy",
    "Sharp",
    "Dead",
    "Mew",
    "Chuckle",
    "Bubba",
    "Bubble",
    "Sandwich",
    "Smasher",
    "Extreme",
    "Multi",
    "Universe",
    "Ultimate",
    "Death",
    "Ready",
    "Monkey",
    "Elevator",
    "Wrench",
    "Grease",
    "Head",
    "Theme",
    "Grand",
    "Cool",
    "Kid",
    "Boy",
    "Girl",
    "Vortex",
    "Paradox",
  ];
  return nameList[Math.floor(Math.random() * nameList.length)];
}
